-- CREATE TABLE posts {
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     title TEXT NOT NULL,
--     content TEXT NOT NULL,
--     author_id INTEGER,
--     created_at TEXT DEFAULT (CURRENT_TIMESTAMP),
--     updated_at TEXT DEFAULT (CURRENT_TIMESTAMP),
-- };

-- -- table de liaison pour les posts et les catégories, 
-- -- pour répondre à l'impossibilité d'entrer une slice d'int dans un champ ? ---