
PRAGMA foreign_keys = ON;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserName TEXT NOT NULL UNIQUE,
    Age INTEGER NOT NULL,
    Gender TEXT NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    userOnline INTEGER DEFAULT 0 /* 0 = hors ligne | 1 = en ligne */
);

CREATE TABLE category (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE
);

/* Contient des comments */
CREATE TABLE post (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Content TEXT NOT NULL,
    AuthorID INTEGER NOT NULL,  /* Changé de TEXT à INTEGER */
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CategoryIDs INTEGER,
    FOREIGN KEY(AuthorID) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(CategoryIDs) REFERENCES category(ID) ON DELETE SET NULL
);

/* Se trouve dans un post */
CREATE TABLE comments (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,    
    PostID INTEGER NOT NULL,
    AuthorID INTEGER NOT NULL,  /* Changé de TEXT à INTEGER */
    Content TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PostID) REFERENCES post(ID) ON DELETE CASCADE,
    FOREIGN KEY (AuthorID) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE messages (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SenderID INTEGER NOT NULL,    /* Changé de TEXT à INTEGER */
    ReceiverID INTEGER NOT NULL,  /* Type ajouté */
    Content TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SenderID) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (ReceiverID) REFERENCES users(id) ON DELETE CASCADE  /* Virgule enlevée */
);